server:
  port: 8090

logging:
  level:
    com.ai.commentbot: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.outh2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE

spring:
  #Local MongoDB config
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: shreeramLearning
      port: 27017
      host: localhost

